title: Theory and Practice
email: bmoseley@buffalo.edu
description: >- 
  Theory and Practice is the annual journal of the Music Theory Society of New York State.
baseurl: ""
url: "tnp.mtsnys.org" 
volume: "Volume 38 | Spring 2024"
editors:
  - name: Trevor de Clercq
  - name: Kyle Hutchinson
reviews_editor:
  name: Daphne Tan

# Build settings
plugins:
  - jekyll-feed
  
# keep junk off the web
exclude:
    - Gemfile
    - Gemfile.lock
    - CNAME
    - README.md

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/